language: cpp
sudo: required
group: travis_latest

matrix:
  include:
    - os: linux
      env: COMPILER=gcc COMPILER_VER=7 CMAKE_VER=3.10.2
    #- os: linux
    #  env: COMPILER=clang COMPILER_VER=5.0 CMAKE_VER=3.10.2
    - os: osx
      osx_image: xcode9.2
      env: COMPILER=gcc COMPILER_VER=7 CMAKE_VER=3.10.2
    #- os: osx
    #  osx_image: xcode9.2
    #  env: COMPILER=clang COMPILER_VER=5.0 CMAKE_VER=3.10.2

before_install:
  # Add CI scripts to PATH.
  - export PATH=${TRAVIS_BUILD_DIR}/tools:${PATH}

  # Create path for dependencies.
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - mkdir -p ${DEPS_DIR}
  - cd ${DEPS_DIR}

install:
  - ci_install-${COMPILER}.sh ${COMPILER_VER} ${TRAVIS_OS_NAME}
  - ci_install-cmake.sh ${CMAKE_VER} ${TRAVIS_OS_NAME}
  - ci_install-clang.sh 5.0 ${TRAVIS_OS_NAME} false

before_script:
  # Import .bash_profile.
  - |
    EXPORTED_PATHS=""
    while IFS='' read -r LINE || [[ -n "$LINE" ]]; do
        EXPORTED_PATHS=${LINE}:${EXPORTED_PATHS}
    done < ~/path_export
    echo "export PATH=${EXPORTED_PATHS}:${PATH}" >> ~/.bash_profile

    if [ -f ~/.bash_profile ]; then
      source ~/.bash_profile
    fi

  # Check versions of used tools.
  - ${CXX} --version
  - cmake --version
  - clang-format --version
  - which ${CXX}
  - which cmake
  - which clang-format
  - cat ~/path_export

  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - cd ${TRAVIS_BUILD_DIR}

after_script:
  # Check code format using clang-format.
  - ci_format.sh .
