language: cpp
sudo: required
group: travis_latest

matrix:
  include:
    - os: linux
      env: COMPILER=gcc COMPILER_VER=8 CMAKE_VER=3.12.0
    - os: linux
      env: COMPILER=clang COMPILER_VER=6.0.1 CMAKE_VER=3.12.0
    #- os: osx
    #  osx_image: xcode9.4
    #  env: COMPILER=gcc COMPILER_VER=8 CMAKE_VER=3.12.0
    - os: osx
      osx_image: xcode9.4
      env: COMPILER=clang COMPILER_VER=6.0.1 CMAKE_VER=3.12.0

before_install:
  # Add CI scripts to PATH.
  - export PATH=${TRAVIS_BUILD_DIR}/tools/ci:${PATH}

  # Create path for dependencies.
  - mkdir -p deps
  - cd deps

install:
  - install-${COMPILER}.sh ${COMPILER_VER} ${TRAVIS_OS_NAME}
  - install-cmake.sh ${CMAKE_VER} ${TRAVIS_OS_NAME}
  - install-clang.sh 6.0.1 ${TRAVIS_OS_NAME} false

before_script:
  - export-paths.sh
  - source ${HOME}/.bash_profile

  # Check versions of used tools.
  - cmake --version
  - clang-format --version

  - cd ${TRAVIS_BUILD_DIR}

script:
  # Build.
  - mkdir -p build
  - cd build
  - cmake -DLIBALLOCATOR_TESTS=ON ..
  - make

  # Run tests.
  - ctest -R UnitTests
  - cd -

after_script:
  # Check code format using clang-format.
  - check-format.sh .
