language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-format-5.0

install:

  - |
    # Linux
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      tools/ci_install-cmake.sh 3.10.1 Linux;
      tools/ci_install-gcc-embedded.sh 7.2 Linux;
    fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
