language: cpp
sudo: required
group: travis_latest

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER_VER=7.2.0 CMAKE_VER=3.10.2
    #- os: linux
    #  compiler: clang
    #  env: COMPILER_VER=5.0 CMAKE_VER=3.10.2
    - os: osx
      osx_image: xcode9.2
      compiler: gcc
      env: COMPILER_VER=7.2.0 CMAKE_VER=3.10.2
    #- os: osx
    #  osx_image: xcode9.2
    #  compiler: clang
    #  env: COMPILER_VER=5.0 CMAKE_VER=3.10.2

before_install:
  # Add CI scripts to PATH.
  - export PATH=${TRAVIS_BUILD_DIR}/tools:${PATH}

  # Create path for dependencies.
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - mkdir -p ${DEPS_DIR}
  - cd ${DEPS_DIR}

install:
  # Compiler.
  - |
    if [ "${CC}" == "gcc" ]; then
      ci_install-gcc.sh ${COMPILER_VER} ${TRAVIS_OS_NAME}
    elif [ "${CC}" == "clang" ]; then
      ci_install-clang.sh ${COMPILER_VER} ${TRAVIS_OS_NAME}
      MAJOR_VER=`echo ${COMPILER_VER} | cut -d . -f 1-2`
      export CC=clang-${MAJOR_VER}
      export CXX=clang-${MAJOR_VER}
    else
      ci_install-gcc-embedded.sh ${COMPILER_VER} ${TRAVIS_OS_NAME}
      export CC=arm-none-eabi-gcc
      export CXX=arm-none-eabi-g++
      export PATH=${DEPS_DIR}/gcc-embedded/bin:${PATH}
    fi

  # CMake.
  - ci_install-cmake.sh ${CMAKE_VER} ${TRAVIS_OS_NAME}

  # Clang-format.
  - ci_install-clang.sh 5.0 ${TRAVIS_OS_NAME}

before_script:
  # Import .bash_profile.
  - |
    if [ -f ~/.bash_profile ]; then
      source ~/.bash_profile
    fi

  # Check versions of used tools.
  - ${CXX} --version
  - cmake --version
  - clang-format --version

  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - cd ${TRAVIS_BUILD_DIR}

after_script:
  # Check code format using clang-format.
  - ci_format.sh .
