language: cpp

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

install:

  - |
    tools/ci_install-cmake.sh 3.10.2 $TRAVIS_OS_NAME;
    tools/ci_install-clang.sh 5.0.1 $TRAVIS_OS_NAME;

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 ..
  - make
