language: cpp

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      
install:

  - |
    # Linux
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      tools/ci_install-cmake.sh 3.10.1 Linux;
      tools/ci_install-clang.sh 5.0.1 Linux;
    fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
